### ISSUE TITLE
`npm install` fails on Linux 64, `yarn install` works

### ISSUE THREAD

**Issue by btbonval** [hunterlester/safe-app-base#1]
Using commit 0512dc13f2f5fa0d323501f12d3a955d0641e37a.

The README.md says:
```
# Set env variable for mock routing
*nix: `set NODE_ENV='dev'`, Windows: `$env:NODE_ENV = 'dev'`
# Install dependencies
npm install
```

On Linux 64-bit, I tried the following:
```
export NODE_ENV=dev
npm install
```

Note that `export` does the same thing as `set` above. I get the following error:
```
Downloading tmp-10713-1-safe_app-mock-v0.4.0-linux-x64.zip
[============================================>] 100.0% of 3.32 MB (1.02 MB/s)
Downloaded and unzip of safe_app-mock complete: 
 - src/native/libsafe_app.so




> electron@1.4.15 postinstall /home/mint/Downloads/m1/safe-app-base/node_modules/electron
> node install.js


> base-safe-app@1.0.0 postinstall /home/mint/Downloads/m1/safe-app-base
> npm run build-safe-app && npm run rebuild


> base-safe-app@1.0.0 build-safe-app /home/mint/Downloads/m1/safe-app-base
> cd node_modules/safe-app && npm install

sh: 1: cd: can't cd to node_modules/safe-app

npm ERR! Linux 4.4.0-53-generic
npm ERR! argv "/home/mint/.nvm/versions/node/v7.10.1/bin/node" "/home/mint/.nvm/versions/node/v7.10.1/bin/npm" "run" "build-safe-app"
npm ERR! node v7.10.1
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! base-safe-app@1.0.0 build-safe-app: `cd node_modules/safe-app && npm install`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the base-safe-app@1.0.0 build-safe-app script 'cd node_modules/safe-app && npm install'.
```

The key bit in the error: `sh: 1: cd: can't cd to node_modules/safe-app`. I checked by hand and `node_modules/safe-app` is absent.

Since every project seems to be moving towards using yarn, I tried the following just for fun.

```
export NODE_ENV=dev
yarn install
```

Yarn ran a bunch of tests, ran through all the post-install stuff, and completed after 388.53 seconds. I was then able to run `npm start` or `yarn start` (both worked the same way): the app executed without any problem.

It looks like the README.md should be updated to make use of `yarn` over `npm`. I'd be happy to submit a PR with `s/npm install/yarn install/g` in the README if that makes it easier.

**Comment by hunterlester** [comment]
@btbonval Hi Bryan! Thank you for taking the time and effort to test and point out these items. I'll take a look when time permits during this week. The `safe-app` dependency may now be automatically installing under the `@maidsafe` directory in `node_modules` now.

**Comment by hunterlester** [comment]
I just pushed an update to this repo.
